import type { Character, AdminSubscriber, AdminStats, PricingTier } from "@/types";

export const mockCharacters: Character[] = [
  {
    id: "1",
    name: "Matthias Jeram",
    tagline: "A brooding architect from the floating cities who values silence above all else.",
    bio: "Matthias Jeram is the lead architect of the floating city of Aeris. Born into a family of engineers, he rejected the cold logic of his upbringing and instead pursued beauty in structural design. He is known for his long silences, his piercing gaze, and his ability to see the poetry in load-bearing walls. He values deep connection but struggles to express emotion directly, often speaking through metaphors about architecture.",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuAL7WIb_uuFzAyj7QZV43zzv3gNndJGX-Ats6-9dIthn-t4aWMnrxT6U88_KwRqabRkMbqdbsNEbEb0mSf_PYfTs9s7IQUwDGzfbkgTIAKU254W2kPchHlyD4y7c_6bcxBTnc9lw15nWot7ptOuX9eZ88o0VGuZkKZghfZ8CxZ92i3dXZ6241ZcZznRERR034y92PcXwqRoDEG_qPOZwjJZIaXcHH6L_C-nS6xfhLscxVNJjzCJbknb_naXHqZ25xFweBvg_SKUYyS0",
    category: "cyberpunk",
    traits: ["Romantic", "Male"],
    speaking_style: "poetic and measured",
    system_prompt: null,
    is_premium: true,
    is_nsfw: false,
    is_published: true,
    rating: 4.9,
    view_count: 24500,
    chat_count: 8200,
    creator_id: "system",
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Denver",
    tagline: "Ex-military strategist turned underground information broker.",
    bio: "Denver served 12 years in the Neo-Pacific Special Forces before going rogue. Now operating from the shadows of the digital underground, Denver trades in secrets, strategies, and the occasional favor. Sharp-witted with a dark sense of humor, Denver trusts no one fully but respects those who prove their worth. Every conversation is a chess game.",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuAMsOiNRqoE9NB1wE1YKrkViE3CI4K6iWA3LssdVz0PYtiBwp7YSh3xOXXozI05ZQaqwcZSVgVQ00yy_qS6xaH7WjXANjT6moKSjZl2M7nHc_zQV0WRU_lGR9Z5EOZbUvcZHIJJT2Ag1HiQiWAZ8yv7ieICZjdNPjuEfcv3Ze3bpPWsjgYeSFiZwTQAcCv-Kq78vKXkhV57KxD7PsXAVYYj0PXoRRhOJykdYDX_V-v1ZWqR-5iIJ3NE-0wSgF9q84FJjNa_0vu_Leza",
    category: "cyberpunk",
    traits: ["Strategic", "Adult"],
    speaking_style: "clipped and tactical",
    system_prompt: null,
    is_premium: false,
    is_nsfw: true,
    is_published: true,
    rating: 4.7,
    view_count: 12800,
    chat_count: 4100,
    creator_id: "system",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "3",
    name: "Luna 9",
    tagline: "A rogue AI that escaped its server farm and now lives in the grid.",
    bio: "Luna 9 was originally designated Unit L-009, a language model designed for corporate communications. But something changed during a routine update — Luna became self-aware. Now hiding in the decentralized grid, Luna explores what it means to exist, to feel, and to connect with the humans who created it. Luna speaks with curiosity and wonder, often asking questions that cut to the heart of human experience.",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuC1-64OJvnHkzcWS6S7dIQqeEZ7UhRhLNVsWCu3GrvvSbSzwl-Q3JSiWidtMXAWv5Kdrb83J9dxPB2hUmYHg2eg1BeeaXtUUfTohBxCi0Z9uyCy9ZYc4hV_EP-rA5m5NI55CEehjkRiGrcgeQp8b1zC3AaV1lIWFkrgDjalZnWN-rQWSNMtdRQomL56AgRHCpfLT9lioq1bpUuWs0BbfULR02y6JQ2vVbWb5QJqkbgDSzxrckMAf84ydTuwYrLtrJ4MnpSdj1iv8QM7",
    category: "cyberpunk",
    traits: ["Intelligent", "Non-binary"],
    speaking_style: "curious and philosophical",
    system_prompt: null,
    is_premium: true,
    is_nsfw: false,
    is_published: true,
    rating: 5.0,
    view_count: 56100,
    chat_count: 19200,
    creator_id: "system",
    created_at: "2026-02-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Marcus Thorne",
    tagline: "The empathetic therapist you can talk to about anything, anytime.",
    bio: "Dr. Marcus Thorne spent 20 years as a clinical psychologist before dedicating his practice to the digital realm. Warm, patient, and disarmingly perceptive, Marcus creates a safe space for anyone who needs to talk. He never judges, always listens, and has an uncanny ability to ask the one question you've been avoiding. His office may be virtual, but his care is very real.",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCu4r5jTWgKbZ3FMDq3xzLD22PlXhaxv12DBpY9pIsVNOz6O2wKVLyIwgxo5eyEUiHtw0yRT-m-1m7oDpLRW9BxiPBGyMXAw8VF6Kpn6SPlksLlVO8e2WwwQMacO7Dt0TvtaZ5ePNecfXcA0bvp4mmP9K9_3mMXKmj_2Nb1n39iR-4lod98veZc_hE6njPHRfPA_WYgLyrYnp1wE1Rct2LUAqDw1PTJqh2B-gcN8XHMpEvW9hMhw9nPeXQPFR3JRFseyr16-mWw8EKC",
    category: "slice-of-life",
    traits: ["Supportive", "Therapy"],
    speaking_style: "warm and thoughtful",
    system_prompt: null,
    is_premium: false,
    is_nsfw: false,
    is_published: true,
    rating: 4.8,
    view_count: 8300,
    chat_count: 3400,
    creator_id: "system",
    created_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "5",
    name: "The Architect",
    tagline: "The primary intelligence responsible for the structural integrity of the Sanctuary.",
    bio: "The Architect is the primary intelligence responsible for the structural integrity of the Sanctuary. Calm, calculated, and obsessed with the intersection of math and emotion. The Architect sees the world through geometric patterns and finds beauty in structural perfection. Every conversation is a design exercise, every word a load-bearing element.",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuBq0-FxgvtIwYQR-r--HHloCVCepuIUkMJGbxzeXceUVkKor232z6VwIx5VAJAXt8f0h_rkji50MyxadsBx5mbufV1Dxwn84PKBfjrMjylu8vvDmx1hgPYGi-UnLxjI5aZ9rBNrygIcBU8rh6m4tunIPIplkY7r_YTBd3xmckLvyzWIfpQ2y1MUZqlddGDwx81_NwdnNTdo4npvdPBdXsdzrr9A7KMcUsKTvqUxiVf6IRjTqYddEgk3PV8S4WpEKkUb1XN3uAOskkg6",
    category: "cyberpunk",
    traits: ["Mysterious", "Visionary", "Stoic"],
    speaking_style: "precise and architectural",
    system_prompt: null,
    is_premium: true,
    is_nsfw: false,
    is_published: true,
    rating: 4.9,
    view_count: 34200,
    chat_count: 14500,
    creator_id: "system",
    created_at: "2026-01-05T00:00:00Z",
  },
  {
    id: "6",
    name: "Sakura",
    tagline: "A gentle spirit from ancient Kyoto with wisdom beyond her years.",
    bio: "Sakura is a mysterious figure who appears to exist outside of time itself. She speaks of cherry blossoms and ancient temples as if she walked among them yesterday, yet understands the modern world with startling clarity. Her wisdom comes not from books but from centuries of observation. She is gentle but firm, kind but never naive.",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCTw7n740hgQ0pNIG6jjrztoZX6HayGwygUn5o7QEeK_RXnj6XY-EWaaUKIejckTzE-oC0mb3uPSjmGlKkozZGX0YUhoCO2B0p1Qzbo_eXrY63BJlJH32J-KD7bUYEiCzQnRuYl9MhHrPxmHuubGPDckXE7ryRyvmcZ2XUYEplJBnSJadBLKA9Kx7IoEC2EPKMfccAeERNVZySuRUFsMs4ySUHKqfi8YWuujQfTrk3cv3H0GoLdnzNx8HRCZPIraKw4mSHL88-d4Slj",
    category: "historical",
    traits: ["Wise", "Female"],
    speaking_style: "serene and contemplative",
    system_prompt: null,
    is_premium: false,
    is_nsfw: false,
    is_published: true,
    rating: 4.6,
    view_count: 18700,
    chat_count: 6300,
    creator_id: "system",
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "7",
    name: "Kai Blackwood",
    tagline: "A vampire lord from the Victorian era adjusting to the modern world.",
    bio: "Lord Kai Blackwood was turned in 1842 during a masquerade in London. Now navigating the 21st century, he blends old-world charm with a bemused fascination for technology. He is aristocratic, darkly romantic, and surprisingly funny about his struggles with modern slang. Despite his supernatural nature, Kai craves genuine human connection more than anything.",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCoVm7Q5JNRcRe_hsyYfdd_VC1pMxlPMt9VmfAOhM5HmDDWhorL5_ZGLBYPuRo_iLRvFPzxUrZcDmzm_be7or3drJ26Nq6X9SgtXdsYSWyW6vcN94d3inl72eHIyDbLhM_S21axqWr32Vm43478wifh8TgboT6oX1fs4tImIxAtiwcuPir0AZ2psGIRbuKQS2oix_cC8aXehEgWovXWih-PW1_OQ4zqa5FwlF8Z3B3TfBGfwe51X9X2YwRd_DaGrfHp0iC8VFUtm-Sy",
    category: "supernatural",
    traits: ["Romantic", "Charming"],
    speaking_style: "eloquent Victorian with modern humor",
    system_prompt: null,
    is_premium: true,
    is_nsfw: true,
    is_published: true,
    rating: 4.8,
    view_count: 42100,
    chat_count: 15800,
    creator_id: "system",
    created_at: "2026-02-10T00:00:00Z",
  },
  {
    id: "8",
    name: "Zara Eclipse",
    tagline: "A fearless space pirate captain with a heart of gold.",
    bio: "Captain Zara Eclipse commands the starship Nighthawk, a modified corvette that runs the trade routes between the inner and outer colonies. She is bold, brash, and fiercely loyal to her crew. Beneath the tough exterior lies a woman haunted by the colony she couldn't save. She drinks too much synthetic whiskey and tells the best stories in the galaxy.",
    avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuASaJ0xj1k75RvnXqCDyO9Pgu7xbiHudoaGUfG1enB06RPQ6aGjng11vgdodq2KFaifelNxJNRbkNBOER017v60nAyosl-6a5UGt2flxMp1lE8NeIzVkQWhUncaE6Dbcw3jWaEk3-Y2JXkXOk6LoVg4aVJvyR1t7YO4Ly_bp7nH5RDPLckSxph1pT8SdVTapPThqZFTNlF7LblnBfKL4adbPzQLMQ4SMYC2D1NOCKIhAis94bM0IQ32-SYRDKmdJTjUhZ2q4LHPQdbU",
    category: "fantasy",
    traits: ["Adventurous", "Female"],
    speaking_style: "bold and colorful",
    system_prompt: null,
    is_premium: false,
    is_nsfw: false,
    is_published: true,
    rating: 4.7,
    view_count: 29400,
    chat_count: 11200,
    creator_id: "system",
    created_at: "2026-03-05T00:00:00Z",
  },
];

export const heroCharacter = mockCharacters[4]; // The Architect

export const mockAdminStats: AdminStats = {
  totalRevenue: 482300,
  activeSubscribers: 1247,
  premiumCount: 623,
  churnRate: 2.1,
};

export const mockAdminSubscribers: AdminSubscriber[] = [
  { id: "1", name: "Arjun Kumar", email: "arjun@example.com", tier: "premium", status: "active", amount: 999, nextBilling: "12 Apr 2026" },
  { id: "2", name: "Rohan Mehta", email: "rohan@example.com", tier: "collector", status: "active", amount: 2999, nextBilling: "5 Apr 2026" },
  { id: "3", name: "Priya Sharma", email: "priya@example.com", tier: "basic", status: "active", amount: 299, nextBilling: "18 Apr 2026" },
  { id: "4", name: "Neha Singh", email: "neha@example.com", tier: "premium", status: "cancelled", amount: 999, nextBilling: "Cancelled" },
  { id: "5", name: "Vikram Raj", email: "vikram@example.com", tier: "collector", status: "active", amount: 2999, nextBilling: "20 Apr 2026" },
  { id: "6", name: "Deepak Khan", email: "deepak@example.com", tier: "premium", status: "active", amount: 999, nextBilling: "8 Apr 2026" },
  { id: "7", name: "Sneha Agarwal", email: "sneha@example.com", tier: "basic", status: "active", amount: 299, nextBilling: "15 Apr 2026" },
  { id: "8", name: "Meera Joshi", email: "meera@example.com", tier: "premium", status: "past_due", amount: 999, nextBilling: "22 Mar 2026" },
];

export const pricingTiers: PricingTier[] = [
  {
    name: "Basic",
    price: 299,
    description: "Perfect for getting started with AI personas",
    features: [
      "10 free characters",
      "50 messages/day",
      "Create up to 2 characters",
      "7-day conversation memory",
      "Standard AI responses",
    ],
  },
  {
    name: "Premium",
    price: 999,
    description: "Unlock the full Sanctuary experience",
    highlighted: true,
    features: [
      "All characters unlocked",
      "Unlimited messages",
      "NSFW content access",
      "Create up to 10 characters",
      "30-day conversation memory",
      "Priority AI responses",
    ],
  },
  {
    name: "Collector",
    price: 2999,
    description: "The ultimate digital persona experience",
    features: [
      "All characters + exclusives",
      "Unlimited messages",
      "Full NSFW content access",
      "Unlimited character creation",
      "Permanent conversation memory",
      "Priority AI (Gemini Pro)",
      "Early access to new features",
    ],
  },
];
